export const ADD_BUSINESS = 'ADD_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';

export const SWITCH_BUSINESS_TAB = 'SWITCH_BUSINESS_TAB';

export const SAVE_CURRENT_STOPWATCH_TIME = 'SAVE_CURRENT_STOPWATCH_TIME';
export const CLEAR_CURRENT_STOPWATCH_TIME = 'CLEAR_CURRENT_STOPWATCH_TIME';

export const SAVE_TIMER_TIME = 'SAVE_TIMER_TIME';
export const CLEAR_CURRENT_COUNTDOWN_TIME = 'CLEAR_CURRENT_COUNTDOWN_TIME';

export const STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER = 'STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER';

export const ADD_WORKING_HOURS = 'ADD_WORKING_HOURS';

export const SAVE_CURRENT_MINI_STOPWATCH_TIME = 'SAVE_CURRENT_MINI_STOPWATCH_TIME';
export const INCREASE_TIMER = 'INCREASE_TIMER';


// STOPWATCH 

export const UPDATE_STOPWATCH = 'UPDATE_STOPWATCH';
export const CLEAR_STOPWATCH = 'CLEAR_STOPWATCH';

export const SAVE_TIMER_ID = 'SAVE_TIMER_ID';

// DATABASE

export const FETCH_BUSINESSDATA_BEGIN   = 'FETCH_BUSINESSDATA_BEGIN';
export const FETCH_BUSINESSDATA_SUCCESS = 'FETCH_BUSINESSDATA_SUCCESS';
export const FETCH_BUSINESSDATA_FAILURE = 'FETCH_BUSINESSDATA_FAILURE';


export const CLEAR_STATE = 'CLEAR_STATE';






